INSERT INTO safety_incidents (incident_id, machine_id, incident_date, severity, description, corrective_action, resolved) VALUES
(1, 1, '2024-01-10', 'HIGH', 'Hydraulic line rupture near press', 'Replaced hydraulic line and added shielding', TRUE),
(2, 2, '2024-01-18', 'MEDIUM', 'Robot arm exceeded safe speed limit', 'Recalibrated speed sensors and updated firmware', TRUE),
(3, 3, '2024-02-02', 'LOW', 'Minor oil leak on floor near machine', 'Cleaned area and replaced gasket', TRUE),
(4, 4, '2024-02-14', 'HIGH', 'Emergency stop triggered by overheating', 'Replaced cooling fan and thermal paste', TRUE),
(5, 5, '2024-02-22', 'MEDIUM', 'Spindle guard loose during operation', 'Tightened guard bolts and added locking washers', TRUE),
(6, 6, '2024-03-05', 'LOW', 'Noise level exceeded threshold', 'Added sound dampening enclosure', TRUE),
(7, 7, '2024-03-12', 'HIGH', 'Teach pendant cable caught in joint', 'Rerouted cable and added cable management', TRUE),
(8, 8, '2024-03-20', 'MEDIUM', 'Light curtain false trigger', 'Cleaned sensors and recalibrated', TRUE),
(9, 9, '2024-04-01', 'LOW', 'Minor vibration anomaly detected', 'Balanced rotating components', TRUE),
(10, 10, '2024-04-08', 'HIGH', 'Hydraulic pressure spike', 'Replaced pressure relief valve', TRUE),
(11, 1, '2024-04-15', 'MEDIUM', 'Electrical arc in control panel', 'Replaced contactor and inspected wiring', TRUE),
(12, 2, '2024-04-22', 'LOW', 'Grease buildup on safety sensors', 'Cleaned and scheduled preventive maintenance', TRUE),
(13, 3, '2024-05-03', 'MEDIUM', 'Unexpected motion during maintenance', 'Updated lockout-tagout procedures', TRUE),
(14, 4, '2024-05-10', 'HIGH', 'Drive belt snapped during operation', 'Replaced belt and added tension monitor', TRUE),
(15, 5, '2024-05-18', 'LOW', 'Coolant splash outside containment', 'Extended splash guard', TRUE),
(16, 6, '2024-05-25', 'MEDIUM', 'PLC communication timeout', 'Replaced communication module', FALSE),
(17, 7, '2024-06-02', 'HIGH', 'Collision detection failure', 'Upgraded collision sensors', FALSE),
(18, 8, '2024-06-10', 'LOW', 'Excessive dust accumulation', 'Installed air filtration system', FALSE),
(19, 9, '2024-06-18', 'MEDIUM', 'Battery backup failure during outage', 'Replaced UPS batteries', FALSE),
(20, 10, '2024-06-25', 'HIGH', 'Pressure gauge reading inaccurate', 'Calibrated gauges and added redundant sensor', FALSE)
