# =============================================================================
# S3 Bucket for Glue Table Data
# Stores factory data in Parquet, Delta, and Iceberg formats.
# Data is generated by the Glue ETL job (see aws_glue_etl.tf).
# =============================================================================

resource "aws_s3_bucket" "glue_data" {
  bucket_prefix = "${var.project_prefix}-glue-data-"
  force_destroy = true

  tags = {
    Name = "${var.project_prefix}-glue-data"
  }
}

resource "aws_s3_bucket_public_access_block" "glue_data" {
  bucket = aws_s3_bucket.glue_data.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
