"""Terraform operations: init, plan, apply, destroy, outputs, tfvars."""

from __future__ import annotations

import json
import subprocess
import sys

from .config import SOURCES, TERRAFORM_DIR, console


class TerraformManager:
    def __init__(self) -> None:
        self._tfvars_path = TERRAFORM_DIR / "terraform.tfvars"

    def init_plan_apply(self) -> None:
        console.print("\n[bold]Terraform deployment...[/bold]\n")
        for label, cmd in [
            ("terraform init", ["terraform", "init"]),
            ("terraform plan", ["terraform", "plan", "-out=tfplan"]),
            ("terraform apply", ["terraform", "apply", "tfplan"]),
        ]:
            console.print(f"[cyan]▶ {label}[/cyan]")
            result = subprocess.run(cmd, cwd=TERRAFORM_DIR)
            if result.returncode != 0:
                console.print(f"[red]✗ {label} failed (exit {result.returncode})[/red]")
                sys.exit(1)
            console.print(f"[green]✓ {label}[/green]\n")

    def destroy(self) -> bool:
        console.print("\n[bold]Terraform destroy...[/bold]\n")
        result = subprocess.run(["terraform", "destroy", "-auto-approve"], cwd=TERRAFORM_DIR)
        if result.returncode == 0:
            console.print("[green]✓ Terraform destroy complete[/green]\n")
            return True
        console.print("[red]✗ Terraform destroy failed[/red]\n")
        return False

    def get_outputs(self) -> dict:
        result = subprocess.run(
            ["terraform", "output", "-json"],
            cwd=TERRAFORM_DIR, capture_output=True, text=True,
        )
        if result.returncode != 0:
            return {}
        try:
            raw = json.loads(result.stdout)
            return {k: v.get("value") for k, v in raw.items()}
        except (json.JSONDecodeError, AttributeError):
            return {}

    def print_outputs(self) -> None:
        console.print("\n[bold]Terraform Outputs:[/bold]")
        subprocess.run(["terraform", "output"], cwd=TERRAFORM_DIR)
        console.print()

    def read_tfvar(self, key: str) -> str:
        if not self._tfvars_path.exists():
            return ""
        for line in self._tfvars_path.read_text().splitlines():
            line = line.strip()
            if line.startswith(key) and "=" in line:
                return line.split("=", 1)[1].strip().strip('"')
        return ""

    def read_sources(self) -> list[str]:
        return [key for key in SOURCES if self.read_tfvar(f"enable_{key}") == "true"]

    def generate_tfvars(
        self,
        cloud: str,
        workspace_url: str,
        sources: list[str],
        query_prefix: str,
        catalog_prefix: str,
        analysis_catalog: str,
        creds: dict,
        *,
        aws_region: str = "us-west-2",
        azure_region: str = "westus2",
        workspace_default_storage_url: str = "",
        resource_suffix: str = "",
    ) -> None:
        db_prefix = query_prefix.removesuffix("_query")
        lines = [
            '# Auto-generated by deploy.py',
            f'project_prefix = "lhf-demo"',
            f'cloud          = "{cloud}"',
            "",
            "# Federation sources",
        ]
        for key in SOURCES:
            lines.append(f'enable_{key:10s} = {str(key in sources).lower()}')

        lines += [
            "",
            "# Catalog naming",
            f'catalog_prefix_query   = "{query_prefix}"',
            f'catalog_prefix_catalog = "{catalog_prefix}"',
            f'analysis_catalog       = "{analysis_catalog}"',
            f'db_prefix              = "{db_prefix}"',
            f'resource_suffix        = "{resource_suffix}"',
            "",
            "# Databricks (OAuth U2M via CLI)",
            f'databricks_host = "{workspace_url}"',
            "",
            "# AWS",
            f'aws_region = "{aws_region}"',
            "",
            "# Azure",
            f'azure_region = "{azure_region}"',
        ]

        if workspace_default_storage_url:
            lines += [
                "",
                "# Workspace default storage (cross-tenant)",
                'use_workspace_default_storage = true',
                f'workspace_default_storage_url = "{workspace_default_storage_url}"',
            ]

        for key, val in creds.items():
            if key == "gcp_credentials_json" and val:
                escaped = val.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
                lines.append(f'{key} = "{escaped}"')
            else:
                lines.append(f'{key} = "{val}"')

        self._tfvars_path.write_text("\n".join(lines) + "\n")
        console.print(f"\n[green]✓[/green] Generated {self._tfvars_path}")
